### ISSUE TITLE
Potential typo: argument named "currModel" instead of "json" in app.js?

### ISSUE THREAD

**Issue by TravisWhitehead** [OSU-CS361-W17/project1#1]
The battleship view javascript is giving me the following error:
`ReferenceError: currModel is not defined app.js:7:5`

This is the first few lines of app.js, where the error occurs:
```javascript
var gameModel;

//This function will be called once the page is loaded.  It will get a new game model from the back end, and display it.
$( document ).ready(function() {

  $.getJSON("model", function( json ) {
    displayGameState(currModel);
    gameModel = json;
   });
});
```

It appears that the argument passed to displayGameState should be `json` instead of `currModel`. Either that or I'm missing something.

**Comment by nelsonni** [comment]
@TravisWhitehead Good catch. This has been resolved in 94777e2.
